update Cognitive Services modules for Python to inclue LUIS
MicrosoftDocs/azure-docs-sdk-python pull request #1338
Opened 2021-04-20 19:59 UTC by magrefaat

2021-04-20 20:05 UTC, opbld33 commented
Docs Build status updates of commit _[e282923](https://github.com/magrefaat/azure-docs-sdk-python/commits/e28292332c71b9916464ad6c304188b59dc64702)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/latest/cognitive-services.md](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-1/docs-ref-services/latest/cognitive-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/python/api/overview/azure/cognitive-services?view=azure-python&branch=pr-en-us-1338) (azure-python) | [Details](#user-content-9f93cfe323d310e4a96979da3c3ea210-2a228339)

<a id="9f93cfe323d310e4a96979da3c3ea210-2a228339"></a>
### [docs-ref-services/latest/cognitive-services.md](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-1/docs-ref-services/latest/cognitive-services.md)
 - **Line 195, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/cognitive-services/luis/what-is-luis'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202104201959484695-1338%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RpHwoCf3PJMd4sangt3%2Fsa6o%2FEAnCH%2B19cNCA%2FDrcu0%3D&st=2021-04-20T20%3A00%3A47Z&se=2021-05-21T20%3A05%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 20:16 UTC, opbld32 commented
Docs Build status updates of commit _[ffd1202](https://github.com/magrefaat/azure-docs-sdk-python/commits/ffd1202bb33a6ba1b74637f3be3cadfa6fa974c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/latest/cognitive-services.md](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-1/docs-ref-services/latest/cognitive-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/python/api/overview/azure/cognitive-services?view=azure-python&branch=pr-en-us-1338) (azure-python) | [Details](#user-content-9f93cfe323d310e4a96979da3c3ea210-96939fb4)

<a id="9f93cfe323d310e4a96979da3c3ea210-96939fb4"></a>
### [docs-ref-services/latest/cognitive-services.md](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-1/docs-ref-services/latest/cognitive-services.md)
 - **Line 195, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/cognitive-services/luis/what-is-luis'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202104202010169770-1338%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PmIbbikffTvIH2rwq8JJL8ncn4thmMazbHSmidT3Zb0%3D&st=2021-04-20T20%3A11%3A20Z&se=2021-05-21T20%3A16%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-24 02:58 UTC, scottaddie requested changes

2021-04-24 02:58 UTC, scottaddie commented on docs-ref-services/latest/cognitive-services.md
> +[Learn more](azure/cognitive-services/luis/what-is-luis) about the LUIS and get started with the [LUIS SDK quickstart](https://docs.microsoft.com/azure/cognitive-services/luis/client-libraries-rest-a
```suggestion
[Learn more](/azure/cognitive-services/luis/what-is-luis) about the LUIS and get started with the [LUIS SDK quickstart](/azure/cognitive-services/luis/client-libraries-rest-api).
```

2021-04-25 15:39 UTC, opbld31 commented
Docs Build status updates of commit _[5d0478d](https://github.com/magrefaat/azure-docs-sdk-python/commits/5d0478dd0a061b8f2d292765a9547151970ab502)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/latest/cognitive-services.md](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-1/docs-ref-services/latest/cognitive-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/python/api/overview/azure/cognitive-services?view=azure-python&branch=pr-en-us-1338) (azure-python) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C25%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202104251532394830-1338%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Zuvsmr5%2Fr7TFowEJVzfc3cB4NXs7Pln0kOFdKin9FWI%3D&st=2021-04-25T15%3A34%3A45Z&se=2021-05-26T15%3A39%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-25 15:47 UTC, opbld33 commented
Docs Build status updates of commit _[5d0478d](https://github.com/magrefaat/azure-docs-sdk-python/commits/5d0478dd0a061b8f2d292765a9547151970ab502)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-services/latest/cognitive-services.md](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-1/docs-ref-services/latest/cognitive-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/python/api/overview/azure/cognitive-services?view=azure-python&branch=pr-en-us-1338) (azure-python) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C25%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202104251532496643-1338%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SAs18SqsyugQP3DtysZ3Hi7mVNmIbPvj06QVH0Y9qHw%3D&st=2021-04-25T15%3A42%3A05Z&se=2021-05-26T15%3A47%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-26 21:49 UTC, scottaddie approved these changes

2021-04-26 21:51 UTC, maggiepint approved these changes

2021-04-26 21:51 UTC, merged