Update LUISAuthoringClient constructor
MicrosoftDocs/azure-docs-sdk-python pull request #1341
Opened 2021-04-25 15:46 UTC by magrefaat

2021-04-25 15:53 UTC, opbld33 commented
Docs Build status updates of commit _[72fdeea](https://github.com/magrefaat/azure-docs-sdk-python/commits/72fdeead7409224b34396c5814b05f2b0cbccd04)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-2/docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/python/api/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.luisauthoringclient?view=azure-python&branch=pr-en-us-1341) (azure-python) | [Details](#user-content-0f2607d6a54fcad9dbe6c80575921b4c-29825369)

<a id="0f2607d6a54fcad9dbe6c80575921b4c-29825369"></a>
### [docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-2/docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml)
 - **Line 24, Column 7**: **[Warning-xref-not-found]** `````Cross reference not found: 'CognitiveServicesCredentials'.`````
 - **Line 29, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'LUISAuthoringClientConfiguration'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C25%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202104251546119281-1341%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1uuZBzk8fNj6xffDDDpKVvDRNksQpE9ptSzQ5K4dlnQ%3D&st=2021-04-25T15%3A48%3A04Z&se=2021-05-26T15%3A53%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:51 UTC, scottaddie requested changes

2021-04-27 00:51 UTC, scottaddie commented on docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml
> +    - <xref:CognitiveServicesCredentials>
```suggestion
    - <xref:msrest.authentication.CognitiveServicesCredentials>
```

2021-04-27 12:09 UTC, opbld33 commented
Docs Build status updates of commit _[8509822](https://github.com/magrefaat/azure-docs-sdk-python/commits/8509822f8ac30bd12083f25e44b0477e9a5d67bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-2/docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/python/api/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.luisauthoringclient?view=azure-python&branch=pr-en-us-1341) (azure-python) | [Details](#user-content-0f2607d6a54fcad9dbe6c80575921b4c-6e29fe5d)

<a id="0f2607d6a54fcad9dbe6c80575921b4c-6e29fe5d"></a>
### [docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml](https://github.com/magrefaat/azure-docs-sdk-python/blob/patch-2/docs-ref-autogen/azure-cognitiveservices-language-luis/azure.cognitiveservices.language.luis.authoring.LUISAuthoringClient.yml)
 - **Line 29, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'LUISAuthoringClientConfiguration'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202104271203027212-1341%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MNphkt4fiZ3QctU0RdFzqSSt7lH6xzW9%2F15spSqcpT0%3D&st=2021-04-27T12%3A04%3A02Z&se=2021-05-28T12%3A09%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 10:46 UTC, closed without merging

2021-04-28 10:46 UTC, magrefaat commented
replaced with https://github.com/Azure/azure-sdk-for-python/pull/18368