Add face ov
MicrosoftDocs/azure-docs-sdk-python pull request #1382
Opened 2021-06-21 20:56 UTC by PatrickFarley

2021-06-21 21:08 UTC, opbld30 commented
Docs Build status updates of commit _[e9b2b3b](https://github.com/PatrickFarley/azure-docs-sdk-python/commits/e9b2b3ba1d3ba174d074a89e42b66b551123e025)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dd568fac)

<a id="dd568fac"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202106212056502088-1382%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4ELR%2FJroivP%2FkKzA16c7XLh4Kg6V%2FpUYKbubcLMXSVo%3D&st=2021-06-21T21%3A03%3A11Z&se=2021-07-22T21%3A08%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 21:36 UTC, opbld33 commented
Docs Build status updates of commit _[cf44cce](https://github.com/PatrickFarley/azure-docs-sdk-python/commits/cf44cce31d5194836829b73977b8786aea3176b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-mapping/reference-unified.yml](https://github.com/PatrickFarley/azure-docs-sdk-python/blob/add-face-ov/docs-ref-mapping/reference-unified.yml) | :white_check_mark:Succeeded | |
[docs-ref-mapping/reference-unified.yml.orig](https://github.com/PatrickFarley/azure-docs-sdk-python/blob/add-face-ov/docs-ref-mapping/reference-unified.yml.orig) | :white_check_mark:Succeeded | |
[docs-ref-services/cognitiveservices/face-readme.md](https://github.com/PatrickFarley/azure-docs-sdk-python/blob/add-face-ov/docs-ref-services/cognitiveservices/face-readme.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202106212123565868-1382%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JMeW%2B54GXppuRF1Ab5iGyVBms%2FVBbMzdQNRHdG9sPbE%3D&st=2021-06-21T21%3A31%3A55Z&se=2021-07-22T21%3A36%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 18:09 UTC, PatrickFarley commented
@danieljurek Please review this PR and merge if ready

2021-06-28 20:02 UTC, scbedd requested changes
I actually approve of these changes, but we need to clean up `docs-ref-mapping/reference-unified.yml.orig` before we merge.

2021-06-28 20:02 UTC, scbedd commented on docs-ref-mapping/reference-unified.yml.orig
> +- name: Reference
I think we accidentally included a file from a conflict resolution.

2021-06-28 20:03 UTC, scbedd approved these changes
It's not the end of the world if you forget to clean this up. I'm just gonna get out of the way by approving it.

Please cleanup that extra file.

2021-06-28 21:10 UTC, opbld31 commented
Docs Build status updates of commit _[3c4620b](https://github.com/PatrickFarley/azure-docs-sdk-python/commits/3c4620be0e4f35b3169720f088c17a6d7bef9561)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-mapping/reference-unified.yml](https://github.com/PatrickFarley/azure-docs-sdk-python/blob/add-face-ov/docs-ref-mapping/reference-unified.yml) | :white_check_mark:Succeeded | |
[docs-ref-services/cognitiveservices/face-readme.md](https://github.com/PatrickFarley/azure-docs-sdk-python/blob/add-face-ov/docs-ref-services/cognitiveservices/face-readme.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C28%5Ca92b76e3-3152-c0a9-537b-4d37096a01a1%5CPullRequest%5C202106282104105713-1382%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I5wd0WPFY8P2MR9heYsB84BY4IN95dZQybAx0%2FUpqms%3D&st=2021-06-28T21%3A05%3A50Z&se=2021-07-29T21%3A10%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-28 22:22 UTC, scbedd commented
Thank you! Merging.

2021-06-28 22:22 UTC, merged