{AzureIoT} fixes Azure/azure-sdk-for-python#27252 Description for cre…
MicrosoftDocs/azure-docs-sdk-python pull request #1657
Opened 2022-11-30 05:57 UTC by navba-MSFT

…ate_device_with_sas

 fixes Azure/azure-sdk-for-python#27252

PR to update the description for create_device_with_sas method to "Creates a device identity on IoTHub that will use SAS as authentication method."

2022-11-30 06:08 UTC, opbld33 commented
Learn Build status updates of commit _[9c3d5da](https://github.com/navba-MSFT/azure-docs-sdk-python/commits/9c3d5da5a06d8624dc1763ae38c8a2342d6e3561)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-autogen/azure-iot-hub/azure.iot.hub.IoTHubRegistryManager.yml](https://github.com/navba-MSFT/azure-docs-sdk-python/blob/patch-7/docs-ref-autogen/azure-iot-hub/azure.iot.hub.IoTHubRegistryManager.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/python/api/azure-iot-hub/azure.iot.hub.iothubregistrymanager?view=azure-python&branch=pr-en-us-1657) (azure-python) | [Details](#user-content-ac7b2aabc8f38911a3a43521b2f16003-a0037c98)

<a id="ac7b2aabc8f38911a3a43521b2f16003-a0037c98"></a>
### [docs-ref-autogen/azure-iot-hub/azure.iot.hub.IoTHubRegistryManager.yml](https://github.com/navba-MSFT/azure-docs-sdk-python/blob/patch-7/docs-ref-autogen/azure-iot-hub/azure.iot.hub.IoTHubRegistryManager.yml)
 - **Line 7, Column 3**: **[Warning: xref-not-found]** `````Cross reference not found: 'builtins.object'.`````
 - **Line 40, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 92, Column 7**: **[Warning: xref-not-found]** `````Cross reference not found: 'Union'.`````
 - **Line 92, Column 43**: **[Warning: xref-not-found]** `````Cross reference not found: ','.`````
 - **Line 98, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 160, Column 7**: **[Warning: xref-not-found]** `````Cross reference not found: 'Union'.`````
 - **Line 160, Column 43**: **[Warning: xref-not-found]** `````Cross reference not found: ','.`````
 - **Line 166, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 228, Column 7**: **[Warning: xref-not-found]** `````Cross reference not found: 'Union'.`````
 - **Line 228, Column 43**: **[Warning: xref-not-found]** `````Cross reference not found: ','.`````
 - **Line 234, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 258, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 293, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 328, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 347, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 371, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 432, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 440, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 462, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 481, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 500, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 514, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 522, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 536, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````
 - **Line 555, Column 11**: **[Warning: xref-not-found]** `````Cross reference not found: '<xref:if the HTTP response status is not in >[<xref:200>]<xref:.>'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/a92b76e3-3152-c0a9-537b-4d37096a01a1/202211300557028811-1657/BuildReport?accessString=ffc895bc2abae6d58ead77f7fccfa1c4d6bf30f7a539738d048117b81dc5fb0d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a92b76e3-3152-c0a9-537b-4d37096a01a1?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-30 20:31 UTC, scbedd approved these changes

2022-11-30 21:17 UTC, scbedd requested changes
Actually, I'm revoking my approval. I did a bit of digging and this isn't the correct place to update.

[here](https://github.com/Azure/azure-iot-hub-python/blob/9cacdd19cdae5f3cb6eb59891f8b301cac645bdf/src/azure/iot/hub/iothub_registry_manager.py#L140) is the actual place to update. If you don't update it there, the next release of that package will remove the manual update that you're adding here.

FYI @sima-zhu @danieljurek . No action here, I was just directly pinged which is why I'm looking at this PR.

2022-12-01 04:07 UTC, navba-MSFT commented
> Actually, I'm revoking my approval. I did a bit of digging and this isn't the correct place to update.
> 
> [here](https://github.com/Azure/azure-iot-hub-python/blob/9cacdd19cdae5f3cb6eb59891f8b301cac645bdf/src/azure/iot/hub/iothub_registry_manager.py#L140) is the actual place to update. If you don't update it there, the next release of that package will remove the manual update that you're adding here.
> 
> FYI @sima-zhu @danieljurek . No action here, I was just directly pinged which is why I'm looking at this PR.

@scbedd Thanks for your review. As per your suggestion, I have created the below PR: https://github.com/Azure/azure-iot-hub-python/pull/10

2022-12-01 04:08 UTC, navba-MSFT commented
Closing this PR and tracking it here https://github.com/Azure/azure-iot-hub-python/pull/10

2022-12-01 04:08 UTC, closed without merging